# Generated by Django 4.2.4 on 2023-12-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='category',
            field=models.CharField(choices=[('1', 'sadsad'), ('2', 'sadsada'), ('3', 'asdas'), ('4', 'sdsada'), ('5', 'Zaz'), ('6', 'asdasdas'), ('7', 'BANANI'), ('8', 'SDASDASD'), ('9', 'asdsada'), ('10', 'xcxzcsdfs'), ('11', 'Babab'), ('12', 'ewrwe')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
