# Generated by Django 4.2.4 on 2023-12-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0002_fruit_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='category',
            field=models.CharField(choices=[('BANANI', 'BANANI')], max_length=255),
        ),
    ]
