# Generated by Django 4.2.4 on 2023-12-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0004_alter_fruit_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='category',
            field=models.CharField(choices=[('BANANI', 'BANANI'), ('ZELE', 'ZELE'), ('sadasda', 'sadasda'), ('zwdasasdasd', 'zwdasasdasd'), ('sasda', 'sasda'), ('asdas', 'asdas'), ('sadsad', 'sadsad'), ('NOVA', 'NOVA'), ('zzzzzzzzzZZZZZZZZZZz', 'zzzzzzzzzZZZZZZZZZZz'), ('sadsadsad!!!!!!!!!!1', 'sadsadsad!!!!!!!!!!1')], max_length=255),
        ),
    ]
